json.id product.id
json.name product.name
json.price product.price
json.image_url product.image_url
json.description product.description
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total product.total
json.top_seller product.top_seller
json.inventory_count product.inventory_count
json.created_at product.created_at
json.updated_at product.updated_at
